apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectyou-frontend
  labels:
    app: connectyou-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectyou-frontend
  template:
    metadata:
      labels:
        app: connectyou-frontend
    spec:
      containers:
      - name: connectyou-frontend
        image: "615492648587.dkr.ecr.us-east-1.amazonaws.com/connectyou:7"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: connectyou-frontend-secrets
              key: port
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: connectyoubackend-secrets
              key: jwt-key
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: connectyoubackend-secrets
              key: mongo-uri
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: connectyoubackend-secrets
              key: gemini-key
        - name: ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: connectyoubackend-secrets
              key: allowed-origins
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000  
          initialDelaySeconds: 30
          periodSeconds: 900  
        readinessProbe:
          httpGet:
            path: /health
            port: 3000  
          initialDelaySeconds: 5
          periodSeconds: 900
